### ISSUE TITLE
BetterBotTags not working

### ISSUE THREAD

**Issue by Razzaline** [QbDesu/BetterDiscordAddons#81]
**Describe the bug**
Webhooks tags aren't displaying, and there's console output showing an error.

**To Reproduce**
1. Enable plugin
2. Find a message sent from a webhook (e.g. PluralKit messages)
3. Displays BOT instead of WEBHOOK

**Expected behavior**
Displays WEBHOOK next to a webhook message

**Screenshots**

**Details (please complete the following information):**
 - Addon Name: BetterBotTags
 - Addon Version: 2.0.1
 - Discord Release Channel: Canary

**Additional context**

Console output:
```
BetterBotTags.plugin.js:233 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at BoundPlugin.patch (BetterBotTags.plugin.js:233:43)
    at BoundPlugin.onStart (BetterBotTags.plugin.js:275:30)
    at BoundPlugin.start (0PluginLibrary.plugin.js:3663:54)
    at D.startPlugin (renderer.js:5:34310)
    at D.startAddon (renderer.js:5:34103)
    at D.loadAddon (renderer.js:5:6716)
    at D.loadAddon (renderer.js:5:31520)
    at D.loadAllAddons (renderer.js:5:8814)
    at D.initialize (renderer.js:5:3194)
    at D.initialize (renderer.js:5:30719)
```

**Comment by Miniontoby** [comment]
@Razzaline Please see my Pull Request #83 since it has the fix for this issue.

You can just see the changes I made and then apply them to the plugin file or just copy paste my edited file into the plugin file

If it fixes the problem (which I am sure it does), then you can close this issue afterwards...
